### ISSUE TITLE
error when running script

### ISSUE THREAD

**Issue by g80ner** [andywalden/esm_o365_cfg#1]

**Comment by andywalden** [comment]
Love easy bug fixes, was it bad credentials? I should clean up the error. Thanks.

**Comment by g80ner** [comment]
yes we had the wrong permissions in AzureAD. McAfee documentation tells you
to enable delegated permissions, but the blog you had created for O365
(which is deleted btw, luckily we had a cached copy) tells you to give
Application Permissions.

thanks for the script!

J

**Comment by andywalden** [comment]
News to me...looks like a rough transition for the boards over there. Thanks for the head's up!
